In [5]:
import numpy as np

In [6]:
np.__version__

'2.1.2'

In [15]:
# 1D array
a = np.array([1,2,3])
print(a.shape)
print(a)
print(a.dtype) # data type
print(a.ndim) # no. of dimensions
print(a.size)
print(a.itemsize) # returns size in bytes
print(a[2])
a[2] = 21
print(a)
b = a * np.array([3,4,5])
print(b)

(3,)
[1 2 3]
int64
1
3
8
3
[ 1  2 21]
[  3   8 105]


In [22]:
# python lists and arrays
list = [23,34,45]
np_array = np.array([23, 34,45])
list.append(34)
print(list)

print(np_array)
np_array = np_array + np.array([100]) # adds 100 to each value
np_array =  np_array + np.array([1000, 100, 10]) # have arrays of equal size and shape
print(np_array)

[23, 34, 45, 34]
[23 34 45]
[1123  234  155]


In [24]:
np.square(list)
np.sqrt(np_array)

array([33.51119216, 15.29705854, 12.4498996 ])

In [26]:
np.log(list)

array([3.13549422, 3.52636052, 3.80666249, 3.52636052])

In [27]:
# dot product
l1 = [1,2,3]
l2 = [4,5,6]

dot = 0
for i in range(len(l1)):
    dot += l1[i] * l2[i]
print(dot)

32


In [29]:
# dot product in numpy
a1 = np.array(l1)
a2 = np.array(l2)
dot = np.dot(a1, a2)
dot

np.int64(32)

In [32]:
# alternatively
dot = (a1 * a2).sum()
print(dot)

# another option
dot = a1 @ a2
print(dot)

# numpy arrays are a lot faster than python list

32
32


Multi-dimensional arrays

In [39]:
a = np.array([[1,3,3],[2,3,3], [4,2,2]])
print(a.ndim)
print(a.shape) # (rows, columns)
print([a[2][0]]) # same as print([a[2,0]])

2
(3, 3)
[np.int64(4)]


In [47]:
# slicing
# to return column 0 only
print(a[:,0])
# return whole first row
print(a[0,:])

# transpose - swapping its rows with its columns.
print(a.T)

# calculate inverse - must be square
a = np.array([[1,3],[2,7]])
print(np.linalg.inv(a))

# calculate determinant
print(np.linalg.det(a))

# calculate diagonal matrix
print(np.diag(a))



[1 2]
[1 3]
[[1 2]
 [3 3]]
[[ 7. -3.]
 [-2.  1.]]
1.0
[1 7]
