In [5]:
import numpy as np

In [6]:
np.__version__

'2.1.2'

In [15]:
# 1D array
a = np.array([1,2,3])
print(a.shape)
print(a)
print(a.dtype) # data type
print(a.ndim) # no. of dimensions
print(a.size)
print(a.itemsize) # returns size in bytes
print(a[2])
a[2] = 21
print(a)
b = a * np.array([3,4,5])
print(b)

(3,)
[1 2 3]
int64
1
3
8
3
[ 1  2 21]
[  3   8 105]


In [22]:
# python lists and arrays
list = [23,34,45]
np_array = np.array([23, 34,45])
list.append(34)
print(list)

print(np_array)
np_array = np_array + np.array([100]) # adds 100 to each value
np_array =  np_array + np.array([1000, 100, 10]) # have arrays of equal size and shape
print(np_array)

[23, 34, 45, 34]
[23 34 45]
[1123  234  155]
