In [5]:
import numpy as np

In [6]:
np.__version__

'2.1.2'

In [15]:
# 1D array
a = np.array([1,2,3])
print(a.shape)
print(a)
print(a.dtype) # data type
print(a.ndim) # no. of dimensions
print(a.size)
print(a.itemsize) # returns size in bytes
print(a[2])
a[2] = 21
print(a)
b = a * np.array([3,4,5])
print(b)

(3,)
[1 2 3]
int64
1
3
8
3
[ 1  2 21]
[  3   8 105]


In [22]:
# python lists and arrays
list = [23,34,45]
np_array = np.array([23, 34,45])
list.append(34)
print(list)

print(np_array)
np_array = np_array + np.array([100]) # adds 100 to each value
np_array =  np_array + np.array([1000, 100, 10]) # have arrays of equal size and shape
print(np_array)

[23, 34, 45, 34]
[23 34 45]
[1123  234  155]


In [24]:
np.square(list)
np.sqrt(np_array)

array([33.51119216, 15.29705854, 12.4498996 ])

In [26]:
np.log(list)

array([3.13549422, 3.52636052, 3.80666249, 3.52636052])

In [27]:
# dot product
l1 = [1,2,3]
l2 = [4,5,6]

dot = 0
for i in range(len(l1)):
    dot += l1[i] * l2[i]
print(dot)

32


In [29]:
# dot product in numpy
a1 = np.array(l1)
a2 = np.array(l2)
dot = np.dot(a1, a2)
dot

np.int64(32)

In [30]:
# alternatively
dot = a1 * a2
dot = np.sum(dot)
dot

np.int64(32)